# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.cache/wt} [current_project]
set_property parent.project_path {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip.coe}}
add_files {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip - a21.coe}}
add_files {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip - a22.coe}}
add_files {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip - a31.coe}}
read_vhdl -library xil_defaultlib {
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/artificial_neuron_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/new/csa_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Artificial_Neuron_a21.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/CSA_8b/CSA_8b.srcs/sources_1/new/CSA.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/CSA_8b/CSA_8b.srcs/sources_1/new/FA.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/new/LUT.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/new/rca_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/CSA_8b/CSA_8b.srcs/sources_1/new/RCA_4b.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/new/Twos_complement_input.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/new/Twos_complement_output.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/dadda_mult_8b/dadda_mult_8b.srcs/sources_1/imports/dadda_mult-master/dadda_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/dadda_mult_8b/dadda_mult_8b.srcs/sources_1/imports/dadda_mult-master/dadda_multi.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/sources_1/imports/FPGA y Vivado/CSA_8b/CSA_8b.srcs/sources_1/new/mux_2to1.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/AND.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Artificial_Neuron.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Artificial_Neuron_a22.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Artificial_Neuron_a31.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Neural_Network.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/imports/new/mac_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/imports/new/mac_lut_utils.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/OR.vhd}
  {C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/NOR.vhd}
}
read_ip -quiet {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_ooc.xdc}}]

read_ip -quiet {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21_ooc.xdc}}]

read_ip -quiet {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a22/ROM_a22.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a22/ROM_a22_ooc.xdc}}]

read_ip -quiet {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a31/ROM_a31.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a31/ROM_a31_ooc.xdc}}]

read_ip -quiet {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_weights/ROM_weights.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_weights/ROM_weights_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/constrs_1/imports/FPGA y Vivado/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/constrs_1/imports/FPGA y Vivado/Nexys4DDR_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Neural_Network -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Neural_Network.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Neural_Network_utilization_synth.rpt -pb Neural_Network_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
