# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21.xci
# IP: The module: 'ROM_a21' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_a21'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21.xci
# IP: The module: 'ROM_a21' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/ROM_a21/ROM_a21_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_a21'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
