# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xci
# IP: The module: 'clk_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xci
# IP: The module: 'clk_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/srome/Desktop/ETSIT/TFG/Pablo Ituero/FPGA y Vivado/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/ip/clk_50MHz/clk_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
